config/routes.rb
Mypage::Application.routes.draw do
  post "emails/create"
  get "profiles/index"
  get "profiles/create"

   root 'profiles#index'

end

app/models/email.rb
class Email < ActiveRecord::Base
	belongs_to :profile
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	has_many :emails
	validates :ip, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/emails_controller.rb
class EmailsController < ApplicationController

    def create
    	@email = Email.new(email_params)

	    if @email.save
	    	EmailMailer.email_mailer(@email).deliver
	    	redirect_to root_url, :notice => 'Message was successfully sent.'
	    else
	        redirect_to root_url, :notice => 'Sorry, you have to try again.'
	    end
	end

	private

	 # Never trust parameters from the scary internet, only allow the white list through.
    def email_params
      params.require(:email).permit(:email, :name, :message )
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  respond_to :html, :js

  def index
  	@clicks = Profile.all.count
  end

  def create
  	@ip = request.remote_ip.to_s
  	
	  @profile = Profile.new(ip: "#{@ip}")
  	
    if @profile.save
      flash[:notice] = ""
  	  redirect_to :back
    else
      flash[:error] = ""
      redirect_to :back
	  end
  end

  private

  def profile_params
    params.require(:profile).permit(:ip, :counter)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Vitalijus Desukas</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

<!-- GOOGLE FONTS -->
	<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800|PT+Sans:400,700|Megrim|Lato:400,700,900' rel='stylesheet' type='text/css'>
<!-- -->

<!-- FAVICON -->
  	<%= favicon_link_tag 'favicon.ico' %>

<!-- GOOGLE ANALYTICS -->
	<script>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	  ga('create', 'UA-68976352-1', 'auto');
	  ga('send', 'pageview');

	</script>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>

</head>
<body>
<div id="page_progress"></div>
	<header>
	    <div id="bottom_nav">
	      <ul>
	        <li><a href="#home_page">Home</a></li>
	        <li><a href="#resume_page">Résumé</a></li>
	        <li><a href="#skills_page">Abilities</a></li>
	        <li><a href="#why_me_page">Why me?</a></li>
	        <li><a href="#contact_page">Contact</a></li>
	      </ul>
	    </div>
	</header>

<%= yield %>

<div id="footer">
	&copy;<%= Time.now.year %> - Handcrafted by Vitalijus Desukas<br>
	<%= image_tag "signature.png", alt: "signature", width: 250 %>
</div>
</body>
	<script src="assets/nanobar-master/nanobar.min.js"></script>
	<script>
		var options = {
		    bg: '#fdfdfd',
		    // leave target blank for global nanobar
		    target: null,
		    //target: document.getElementById('myDivId'),
		    // id for new nanobar
		    id: 'page_progress'
		};

		var nanobar = new Nanobar( options );

		//move bar
		nanobar.go(30); // size bar 30%

		// Finish progress bar
		nanobar.go(100);
	</script>
</html>

app/views/profiles/_counter.html.erb
<div id="counter">
	<%= @clicks %>
	<% if  flash[:error] %>
		<div id="error"></div>
	<% elsif flash[:notice] %>
		<div id="notice"></div>
	<% end %>
</div>

app/views/profiles/_skills.html.erb
<!-- SKILLS PAGE -->
<section id="skills_page">
  <div class="page_title">
    Abilities
  </div>

    <div class="skills_list">
    <div class="resume_heading">
      Marketing
    </div>

    <ul>
      <li>
        Search Engine Optimisation (SEO)
        <span class="star_gold">&#9733;&#9733;&#9733;&#9733;&#9733;</span>
      </li>
      <li>
        Email Marketing
        <span class="star_gold">&#9733;&#9733;&#9733;&#9733;&#9733;</span>
      </li>
      <li>
        Social Media Marketing
        <span class="star_grey">&#9733;</span>
        <span class="star_gold">&#9733;&#9733;&#9733;&#9733;</span>
      </li>
      <li>
        Paid Search/SEM
        <span class="star_grey">&#9733;</span>
        <span class="star_gold">&#9733;&#9733;&#9733;&#9733;</span>
      </li>
      <li>
        WEB analytics
        <span class="star_grey">&#9733;</span>
        <span class="star_gold">&#9733;&#9733;&#9733;&#9733;</span>
      </li>
    </ul>

    <ul>
      <li>
        Design (web, mobile)
        <span class="star_grey">&#9733;&#9733;</span>
        <span class="star_gold">&#9733;&#9733;&#9733;</span>
      </li>
      <li>
        Display Advertising
        <span class="star_grey">&#9733;&#9733;</span>
        <span class="star_gold">&#9733;&#9733;&#9733;</span>
      </li>
      <li>
        Affiliate Marketing
        <span class="star_grey">&#9733;&#9733;</span>
        <span class="star_gold">&#9733;&#9733;&#9733;</span>
      </li>
      <li>
        Content Marketing
        <span class="star_grey">&#9733;&#9733;&#9733;</span>
        <span class="star_gold">&#9733;&#9733;</span>
      </li>
      <li>
        Video Marketing
        <span class="star_grey">&#9733;&#9733;&#9733;&#9733;</span>
        <span class="star_gold">&#9733;</span>
      </li>
    </ul>
  </div>

  <div class="skills_list">
    <div class="resume_heading">
      Tools & Techniques
    </div>

    <ul>
      <li>
        CSS(3)
        <span class="star_gold">&#9733;&#9733;&#9733;&#9733;&#9733;</span>
      </li>
      <li>
        HTML(5)
        <span class="star_gold">&#9733;&#9733;&#9733;&#9733;&#9733;</span>
      </li>
      <li>
        WIKI CMS
        <span class="star_gold">&#9733;&#9733;&#9733;&#9733;&#9733;</span>
      </li>
      <li>
        Responsive design
        <span class="star_gold">&#9733;&#9733;&#9733;&#9733;&#9733;</span>
      </li>
      <li>
        Ruby on Rails
        <span class="star_grey">&#9733;</span>
        <span class="star_gold">&#9733;&#9733;&#9733;&#9733;</span>
      </li>
      <li>
        Conversion optimization
        <span class="star_grey">&#9733;</span>
        <span class="star_gold">&#9733;&#9733;&#9733;&#9733;</span>
      </li>
      <li>
        Ruby
        <span class="star_grey">&#9733;&#9733;</span>
        <span class="star_gold">&#9733;&#9733;&#9733;</span>
      </li>
    </ul>

    <ul>
      <li>
        JavaScript
        <span class="star_grey">&#9733;&#9733;</span>
        <span class="star_gold">&#9733;&#9733;&#9733;</span>
      </li>
      <li>
        Jquery
        <span class="star_grey">&#9733;&#9733;</span>
        <span class="star_gold">&#9733;&#9733;&#9733;</span>
      </li>
      <li>
        WordPress CMS
        <span class="star_grey">&#9733;&#9733;</span>
        <span class="star_gold">&#9733;&#9733;&#9733;</span>
      </li>
      <li>
        Contao CMS
        <span class="star_grey">&#9733;&#9733;</span>
        <span class="star_gold">&#9733;&#9733;&#9733;</span>
      </li>
      <li>
        Adobe Photoshop
        <span class="star_grey">&#9733;&#9733;</span>
        <span class="star_gold">&#9733;&#9733;&#9733;</span>
      </li>
      <li>
        Adobe Illustrator
        <span class="star_grey">&#9733;&#9733;&#9733;</span>
        <span class="star_gold">&#9733;&#9733;</span>
      </li>
      <li>
        UI/UX
        <span class="star_grey">&#9733;&#9733;&#9733;</span>
        <span class="star_gold">&#9733;&#9733;</span>
      </li>
    </ul>
  </div>

  <div class="skills_list">
    <div class="resume_heading">
      Languages
    </div>

    <ul>
      <li>
        Lithuanian
        <span class="star_gold">&#9733;&#9733;&#9733;&#9733;&#9733;</span>
      </li>
      <li>
        Russian
        <span class="star_gold">&#9733;&#9733;&#9733;&#9733;&#9733;</span>
      </li>
    </ul>

    <ul>
      <li>
        English
        <span class="star_grey">&#9733;</span>
        <span class="star_gold">&#9733;&#9733;&#9733;&#9733;</span>
      </li>
      <li>
        German
        <span class="star_grey">&#9733;&#9733;</span>
        <span class="star_gold">&#9733;&#9733;&#9733;</span>
      </li>
    </ul>
  </div>
</section>

app/views/profiles/index.html.erb
<div class="landing_image"></div>

<!-- HOME PAGE -->
<section id="home_page">
  <div id="home_page_content">
    <div class="initials_image">
      VD
    </div>

    <div class="name_surname">
      Vitalijus Dešukas
    </div>

    <div class="name_subheader">
      Digital marketer
    </div>

    <a href="#contact_page">
      <div class="contact_button">
        For hire
      </div>
    </a>
  </div>

  <a href="#resume_page">
    <div id="arrow_down">
      <%= image_tag "arrow_down.png" %>
    </div>
  </a>
</section>



<!-- RESUME -->
<section id="resume_page">
  <header>
    <div id="nav-anchor"></div>
    <nav>
      <ul>
        <li><a href="#home_page">Home</a></li>
        <li><a href="#resume_page">Résumé</a></li>
        <li><a href="#skills_page">Abilities</a></li>
        <li><a href="#why_me_page">Why me?</a></li>
        <li><a href="#contact_page">Contact</a></li>
      </ul>
      
      <div class="counter_box">
        <%= render "counter" %>
        <%= link_to '/profiles/create', remote: true do %>
          Handshake
        <% end %>
      </div>
    </nav>
  </header>

  <div class="page_title">
    Résumé
  </div>

  <div class="about_me">
    Experienced marketer with well developed skills in digital marketing, digital project management. I'm determined and enthusiastic, I have developed good planning & organisational skills, & confident working independently or as part of a team.
  </div>

  <div class="resume">
    <div class="resume_heading">
      Work experience
    </div>

    <ul>
      <li class="empl">
        <div class="position_name">
          Digital Marketing Assistant
        </div>

        <div class="company_name">
          AviaTrading
        </div>

        01/09/14 – 01/09/15<br>
        Munich, Germany
      </li>

      <li class="resume_content">
        <div class="work_description">
          I was responsible for the development of new campaigns to drive site traffic, helping to
          improve site content and structure to provide better architecture and usability, whilst
          improving search engine optimisation.
        </div>
      </li>
    </ul>

    <ul>
      <li class="empl">
        <div class="position_name">
          Digital Project Assistant
        </div>

        <div class="company_name">
          Bergx2 GmbH
        </div>

        Nov. 2014 - Feb. 2015<br>
        Munich, Germany
      </li>

      <li class="resume_content">
        <div class="work_description">
          At Bergx2, I was responsible for the acceleration of digital projects, both on the
          organisation’s own web portals and those of new venture companies. I also worked with web
          development teams to ensure project plan is properly implemented.
        </div>
      </li>
    </ul>

    <ul>
      <li class="empl">
        <div class="position_name">
          Working Student
        </div>

        <div class="company_name">
          Allianz AMOS
        </div>
        2012 - 2013<br>
        Munich, Germany
      </li>

      <li class="resume_content">
        <div class="work_description">
          Key responsibilities consisted of developing and maintaining the GloBI (Global Business Intelligence Platform) web page with the WIKI Content Management System, supporting the layout development with HTML and CSS, as well as facilitating managers and the project management office in GloBI maintenance. 
        </div>
      </li>
    </ul>

    <ul>
      <li class="empl">
        <div class="position_name">
          EVS Volunteer
        </div>

        <div class="company_name">
          LISEL asbl
        </div>
        2010 - 2011<br>
        Luxemburg city, Luxemburg
      </li>

      <li class="resume_content">
        <div class="work_description">
          EVS project's aim was to encourage in self-initiative, entrepreneurship and turn ideas into actions. During EVS Vitalijus have developed several projects:<br>
          - Promoted LISEL asbl and raised level of awareness through various media actions.<br>
          - Project's website development and maintenance.<br>
          - Participation in short movie festivals.<br><br>
          
          All this actions takes creativity, innovation, risk-taking, as well as the ability to plan and manage projects in order to achieve objectives.
        </div>
      </li>
    </ul>
  </div>

  <div class="resume">
    <div class="resume_heading">
      Education
    </div>

    <ul>
      <li class="empl">
        <div class="position_name">
          Technical University Munich
        </div>

        <div class="company_name">
          TUM School of Management, Master in Consumer Affairs
        </div>
        2012 - 2014<br>
        Munich, Germany
      </li>
      <li class="resume_content">
        <div class="work_description">
          Advanced studies in digital marketing, innovation management and technologies gave a
        unique view in developing consumer related ideas and concepts.
        </div>
      </li>
    </ul>

    <ul>
      <li class="empl">
        <div class="position_name">
          Lithuanian University of Educational Science
        </div>

        <div class="company_name">
          Bachelor in Sociology
        </div>
        2006 - 2010<br>
        Vilnius, Lithuania
      </li>

      <li class="resume_content"> 
        <div class="work_description">
          Studies in empirical investigation have encouraged me to seek professional future in the area of market research.
        </div>
      </li>
    </ul>
  </div>
</section>

<!-- FOR HIRE -->
<section id="for_hire">
  <div id="for_hire_wrapper">
    <div class="for_hire_title">
      Are you interested in boosting your revenue?
    </div>

    <a href="#contact_page">
      <div class="contact_now_button">
        Contact now
      </div>
    </a>
  </div>
</section>

<%= render "skills" %>

<!-- FOR HIRE -->
  <section id="for_hire">
    <div id="for_hire_wrapper">
      <div class="for_hire_title">
        I will show you how to open doors for consistently profitable traffic
      </div>

      <a href="#contact_page">
        <div class="contact_now_button">
          Contact now
        </div>
      </a>
    </div>
  </section>

<!-- WHY ME PAGE -->
<section id="why_me_page">
  <div class="page_title">
    Why me?
  </div>

  <div class="why_me_reasons">
    <ul>
      <li>
        <span class="reasons_title">Vision</span>
        My vision is to bring your company to success through modern technologies. I will enhance your business with innovative ideas, new concepts and will find the best way to reinforce brand through sophisticated visual design.
      </li>

      <li>
        <span class="reasons_title">Problem-Solver</span>
        Expertise I have acquired over the last several year allows me to identify problem and successfully solve it. This comes very handy regarding human-centered approach, to ensure that positive customer/user experience would be execute on the highest possible level.
      </li>

      <li>
        <span class="reasons_title">Strategic</span>
        A lifestyle entrepreneur. Business-like. I identify growth opportunities. Serve people. Execute plans. Solve problems. Create competitive advantage. Promote personal growth.
      </li>

      <li>
        <span class="reasons_title">Hands-On</span>
        I like getting my hands dirty. This way I can explore every little detail that will bring to ultimate success.
      </li>

      <li>
        <span class="reasons_title">Collaborative</span>
        I like to set clear expectations, share and encourage to share knowledge, say good things about people, ask questions and listen others.
      </li>

      <li>
        <span class="reasons_title">Ambitious</span>
        I'm always looking into the future and searching for new opportunities, and aren't afraid to take risks for the sake of reaching my goal.
      </li>
    </ul>
  </div>

  <!-- RECOMMEDATIONS -->
  <div id="recommendations">
    <div class="page_title">
      Recommendations
    </div>

    <div class="referral">
      <ul>
        <li>
          "I have had the pleasure of viewing Mr. Desukas’ professional development during his work at Allianz AMOS, and I can state with confidence that he is a motivated and responsible person with a high degree of integrity."<br>
          <span class="rec_person"><a href="https://www.linkedin.com/pub/agata-przygoda/2/626/6aa" target="_blank">Agata Przygoda</a></span>
          <span class="position">Executive Assistant - Group COO Office at Allianz Group</span>
        </li>

        <li>
          "I am delighted to have this opportunity to recommend Mr. Vitalijus Desukas. As the owner of the Bergx2 GmbH, I have seen his develop into a dedicated worker with a mind well-adapted to the demands of the business world.
          <span class="rec_person"><a href="https://www.linkedin.com/in/istokistok" target="_blank">Istok Sernc</a></span>
          <span class="position">Managing Director - Bergx2 GmbH</span>
        </li>
      </ul>
    </div>
  </div>
</section>

<!-- CONTACT PAGE -->
<section id="contact_page">
  <div class="page_title contact">
    Contact 
  </div>

  <ul class="contact_container">
    <li class="contact_me">
      Interested in working together or just want to say hello?<br>
      Drop me a line.<br><br>

      <ul class="contact_details">
        <li>
          <%= image_tag "pin.png", alt: "location", width: 20 %>
          London, United Kingdom
        </li>

        <li>
          <%= image_tag "phone.png", alt: "phone number", width: 20 %>
          +44 7435 019669
        </li>

        <li>
          <!--<%= image_tag "mail.png", alt: "email", width: 20 %>
          vitalij.desuk@gmail.com  | hire@vitalijusdesukas.com-->
        </li>
      </ul>
    </li>

    <li class="contact_form">
      <%= form_for Email.new, url: emails_create_path do |f| %>
        <div class="form_field">
          <%= f.text_field :name, :placeholder => "Name(*)", :class => "field" %>
        </div>

        <div class="form_field">
          <%= f.text_field :email, :placeholder => "Email(*)", :class => "field" %>
        </div>

        <div class="form_field">
          <%= f.text_area :message, :placeholder => "Your message here...", :class => "field_message" %>
        </div>

        <div class="button_wrapper">
          <%= f.submit "Send", :class => "form_button" %>
        </div>
      <% end %>
    </li>
  </ul>
</section>

app/views/profiles/index.js.erb
$("#counter").html("<%= j(render('counter')) %>");